language: c++

services:
  - docker

before_install:
  - docker build -t harvard-evolutionary-dynamics/eulerian:latest .
  - docker run --name eulerian_bash --rm -it -d harvard-evolutionary-dynamics/eulerian:latest bash
  - docker ps

script:
  - ls
  - pwd
  - docker exec -t -d eulerian_bash cmake -Wno-dev -DCMAKE_BUILD_TYPE=Release --build cmake-build-release --target test-eulerian -- -j 2 .
  - docker exec -t -d eulerian_bash time ./cmake-build-release/tests/cmake-build-debug/test-eulerian
